### ISSUE TITLE
TreeNavigation doesn't expand when directly visited URL is nested two or more layers

### ISSUE THREAD

**Issue by MelvinFrohike** [J3-Tech/Vue-Tree-Navigation#37]
This seems like a continuation of issue #5:

Suppose I have a structure like this:

* Parent Group
  * Leaf Item no. 1
  * Child Group
    * Leaf Item no. 2
  
When visiting Leaf Item no. 1 directly by entering its URL in the browser, Parent Group is automatically expanded as I would expect.
When visiting Leaf Item no. 2 directly, nothing is expanded. I would expect both Parent Group and Child Group to be expanded.
When I set autoOpenLevel to 1, Child Group gets expanded correctly. If I had other groups next to parent group, they would get expanded as well which is not what I want.

I am using manually defined items.

**Comment by chellem** [comment]
Can you give some code examples?
I'm not able to replicate the issue.  It seems to be working fine in a five level nesting.

**Comment by MelvinFrohike** [comment]
4 years later i can no longer reproduce this. It must have been fixed in the meantime.
